#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade HG on Thu Feb 13 12:47:43 2014

import wx
from MyFrame import MyFrame

class App_adm(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = MyFrame(None, -1, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class App_adm

if __name__ == "__main__":
    adm = App_adm(0)
    adm.MainLoop()
