# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Fri Feb 14 17:06:48 2014
#

import wx
# begin wxGlade: dependencies
import wx.grid
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

import Frm_NewConn


class Frm_Main(wx.Frame):
    
    _Frm_NewConn__server = ''
    
    def __init__(self, *args, **kwds):
        # begin wxGlade: Frm_Main.__init__
        kwds["style"] = wx.CAPTION | wx.CLOSE_BOX | wx.MINIMIZE_BOX | wx.MAXIMIZE_BOX | wx.SYSTEM_MENU | wx.RESIZE_BORDER | wx.FRAME_FLOAT_ON_PARENT | wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.Frm_Main_menubar = wx.MenuBar()
        self.File = wx.Menu()
        self.opc_newcon = wx.MenuItem(self.File, wx.ID_ANY, _("New connection"), "", wx.ITEM_NORMAL)
        self.File.AppendItem(self.opc_newcon)
        self.File.AppendSeparator()
        self.opc_quit = wx.MenuItem(self.File, wx.ID_ANY, _("Quit"), "", wx.ITEM_NORMAL)
        self.File.AppendItem(self.opc_quit)
        self.Frm_Main_menubar.Append(self.File, _("File"))
        self.SetMenuBar(self.Frm_Main_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.Frm_Main_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL | wx.TB_TEXT | wx.TB_HORZ_LAYOUT | wx.TB_HORZ_TEXT)
        self.SetToolBar(self.Frm_Main_toolbar)
        # Tool Bar end
        self.btn_newConn = wx.Button(self, wx.ID_ANY, _("New connection"))
        self.Grd_ListaUsrs = wx.grid.Grid(self, wx.ID_ANY, size=(1, 1))
        self.text_server = wx.TextCtrl(self, wx.ID_ANY, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btn_newConn_Click, self.btn_newConn)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Frm_Main.__set_properties
        self.SetTitle(_("Active Directory Management"))
        self.SetSize((771, 600))
        self.Frm_Main_toolbar.SetToolSeparation(5)
        self.Frm_Main_toolbar.Realize()
        self.Grd_ListaUsrs.CreateGrid(10, 4)
        self.Grd_ListaUsrs.SetColLabelValue(0, _("Name"))
        self.Grd_ListaUsrs.SetColLabelValue(1, _("Surnname"))
        self.Grd_ListaUsrs.SetColLabelValue(2, _("Date"))
        self.Grd_ListaUsrs.SetColLabelValue(3, _("Patata"))
        self.Grd_ListaUsrs.SetMinSize((600,400))
        self.Grd_ListaUsrs.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.Grd_ListaUsrs.SetForegroundColour(wx.Colour(49, 55, 57))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Frm_Main.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.btn_newConn, 0, wx.SHAPED | wx.ADJUST_MINSIZE, 0)
        sizer_1.Add(self.Grd_ListaUsrs, 1, wx.EXPAND, 0)
        sizer_1.Add(self.text_server, 0, wx.ADJUST_MINSIZE, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def btn_newConn_Click(self, event):  # wxGlade: Frm_Main.<event_handler>
        nc = Frm_NewConn.Frm_NewConn(parent=self)
        nc.Show(True)
        nc.MakeModal(True)

# end of class Frm_Main
