# -*- coding: utf-8 -*-
# generated by wxGlade HG on Tue Feb 18 10:06:52 2014

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class Frm_Conn2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Frm_Conn2.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1_copy = wx.StaticText(self, -1, _("Connection Properties"))
        self.label_2_copy = wx.StaticText(self, -1, _("Introduce your connection information\n"))
        self.label_3_copy = wx.StaticText(self, -1, _("Saved configurations"))
        self.combo_box_1_copy = wx.ComboBox(self, -1, choices=[_("Configuration 1"), _("Configuration 2"), _("Configuration 3")], style=wx.CB_DROPDOWN)
        self.label_7_copy = wx.StaticText(self, -1, _("New configuration"))
        self.label_8 = wx.StaticText(self, -1, _("Specify information access"))
        self.label_4_copy = wx.StaticText(self, -1, _("Server"))
        self.txt_server = wx.TextCtrl(self, -1, "")
        self.label_5_copy = wx.StaticText(self, -1, _("CN"))
        self.txt_CN = wx.TextCtrl(self, -1, "")
        self.label_6_copy = wx.StaticText(self, -1, _("Password"))
        self.txt_passwd = wx.TextCtrl(self, -1, "")
        self.btn_ok = wx.Button(self, -1, _("OK"))
        self.btn_cancel = wx.Button(self, -1, _("Cancel"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btn_ok_Click, self.btn_ok)
        self.Bind(wx.EVT_BUTTON, self.btn_cancel_Click, self.btn_cancel)
        # end wxGlade

	self.parent = kwds['parent']

    def __set_properties(self):
        # begin wxGlade: Frm_Conn2.__set_properties
        self.SetTitle(_("frame_2"))
        self.label_1_copy.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Cantarell"))
        self.combo_box_1_copy.SetSelection(-1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Frm_Conn2.__do_layout
        sizer_2_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_3_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1_copy = wx.FlexGridSizer(6, 2, 20, 20)
        sizer_3_copy.Add(self.label_1_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 0)
        sizer_3_copy.Add(self.label_2_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.label_3_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.combo_box_1_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.label_7_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.label_8, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.label_4_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.txt_server, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.label_5_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.txt_CN, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.label_6_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.txt_passwd, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3_copy.Add(grid_sizer_1_copy, 1, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_5.Add(self.btn_ok, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_5.Add(self.btn_cancel, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_3_copy.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_2_copy.Add(sizer_3_copy, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2_copy)
        sizer_2_copy.Fit(self)
        sizer_2_copy.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def btn_ok_Click(self, event): # wxGlade: Frm_Conn2.<event_handler>
		#Recopilamos toda la información introducida por el usuario, comprobamos que esta todo correcto e intentamos lanzar una conexion:
		self.parent.__server    = self.txt_server.GetValue ()
		self.parent.__CN        = self.txt_CN.GetValue ()
		self.parent.__passwd    = self.txt_passwd.GetValue ()
        
        	if ( ( not self.parent.__server ) or ( not self.parent.__CN ) or ( not self.parent.__passwd ) ) :
           		dlg = wx.MessageDialog(self, message='Please, fill in all the blanks.', caption='error:',style=wx.ICON_ERROR )
            		result = dlg.ShowModal() 
            		dlg.Destroy() 
        	else:
            	#Devolvemos 0 o 1 en funcion de si hemos podido conectarnos                    
            		if ( self.parent.__connectToServer () == 0 ):
               	 		dlg = wx.MessageDialog(self, message='Connect error, check data', caption='error:',style=wx.ICON_ERROR )
                		result = dlg.ShowModal() 
                		dlg.Destroy()
            		else:
                		self.MakeModal(False)
                		self.Destroy()

    def btn_cancel_Click(self, event): # wxGlade: Frm_Conn2.<event_handler>
		self.MakeModal(False)
		self.Destroy()
		event.Skip()

# end of class Frm_Conn2


