# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Fri Feb 14 17:06:48 2014
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Frm_NewConn(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Frm_NewConn.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_12 = wx.StaticText(self, wx.ID_ANY, _("Connection Properties"))
        self.label_13 = wx.StaticText(self, wx.ID_ANY, _("Introduce your connection information"))
        self.label_14 = wx.StaticText(self, wx.ID_ANY, _("Server"))
        self.txt_server = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_15 = wx.StaticText(self, wx.ID_ANY, _("CN"))
        self.text_ctrl_10 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_16 = wx.StaticText(self, wx.ID_ANY, _("Password"))
        self.text_ctrl_11 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.btn_ok = wx.Button(self, wx.ID_ANY, _("OK"))
        self.btn_cancel = wx.Button(self, wx.ID_ANY, _("Cancel"))
        self.Frm_NewConn_statusbar = self.CreateStatusBar(1, 0)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btn_ok_Click, self.btn_ok)
        self.Bind(wx.EVT_BUTTON, self.btn_cancel_Click, self.btn_cancel)
        # end wxGlade
        
        self.parent = kwds['parent']

    def __set_properties(self):
        # begin wxGlade: Frm_NewConn.__set_properties
        self.SetTitle(_("New connection"))
        self.label_12.SetFont(wx.Font(18, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Cantarell"))
        self.label_13.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Cantarell"))
        self.btn_ok.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Cantarell"))
        self.btn_cancel.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Cantarell"))
        self.Frm_NewConn_statusbar.SetStatusWidths([-1])
        # statusbar fields
        Frm_NewConn_statusbar_fields = [_("Frm_NewConn_statusbar")]
        for i in range(len(Frm_NewConn_statusbar_fields)):
            self.Frm_NewConn_statusbar.SetStatusText(Frm_NewConn_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Frm_NewConn.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_4 = wx.GridSizer(4, 4, 10, 10)
        grid_sizer_5 = wx.GridSizer(5, 4, 20, 20)
        sizer_6.Add(self.label_12, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(self.label_13, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ADJUST_MINSIZE, 0)
        grid_sizer_5.Add(self.label_14, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_5.Add(self.txt_server, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_5.Add(self.label_15, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_5.Add(self.text_ctrl_10, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_5.Add(self.label_16, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_5.Add(self.text_ctrl_11, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(grid_sizer_5, 3, wx.EXPAND, 0)
        grid_sizer_4.Add(self.btn_ok, 0, wx.ALIGN_RIGHT | wx.ADJUST_MINSIZE, 0)
        grid_sizer_4.Add(self.btn_cancel, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(grid_sizer_4, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_6, 2, wx.EXPAND, 0)
        self.SetSizer(sizer_4)
        sizer_4.Fit(self)
        self.Layout()
        # end wxGlade

    def btn_cancel_Click(self, event):  # wxGlade: Frm_NewConn.<event_handler>
        self.MakeModal(False)
        self.Destroy()
        event.Skip()
    def btn_ok_Click(self, event):  # wxGlade: Frm_NewConn.<event_handler>
        self.parent.__server =("patata")
        self.parent.text_server.SetValue ( self.txt_server.GetValue ())
        self.MakeModal(False)
        self.Destroy()
        event.Skip()

        
# end of class Frm_NewConn
