# -*- coding: utf-8 -*-
# generated by wxGlade HG on Tue Feb 18 09:38:05 2014

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class Frm_Conn(wx.MDIChildFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Frm_Conn.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.CLIP_CHILDREN
        wx.MDIChildFrame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.frame_1_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_1_toolbar)
        # Tool Bar end
        self.label_1 = wx.StaticText(self, -1, _("Connection Properties"))
        self.label_2 = wx.StaticText(self, -1, _("Introduce your connection information\n"))
        self.label_3 = wx.StaticText(self, -1, _("Saved configurations"))
        self.combo_box_1 = wx.ComboBox(self, -1, choices=[_("Configuration 1"), _("Configuration 2"), _("Configuration 3")], style=wx.CB_DROPDOWN)
        self.label_7 = wx.StaticText(self, -1, _("New configuration"))
        self.label_4 = wx.StaticText(self, -1, _("Server"))
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
        self.label_5 = wx.StaticText(self, -1, _("CN"))
        self.text_ctrl_2 = wx.TextCtrl(self, -1, "")
        self.label_6 = wx.StaticText(self, -1, _("Password"))
        self.text_ctrl_3 = wx.TextCtrl(self, -1, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Frm_Conn.__set_properties
        self.SetTitle(_("frame_1"))
        self.frame_1_toolbar.Realize()
        self.label_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Cantarell"))
        self.combo_box_1.SetSelection(-1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Frm_Conn.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(6, 2, 15, 15)
        sizer_3.Add(self.label_1, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(self.label_2, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_3, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.combo_box_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_7, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_4, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_5, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_2, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_6, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_3, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(grid_sizer_1, 1, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Frm_Conn


