# -*- coding: utf-8 -*-
# generated by wxGlade HG on Tue Feb 18 11:58:03 2014

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_9 = wx.StaticText(self, -1, _("Connections Properties"))
        self.label_10 = wx.StaticText(self, -1, _("Saved configurations"))
        self.combo_box_2 = wx.ComboBox(self, -1, choices=[_("Configuration 1"), _("Configuration 2")], style=wx.CB_DROPDOWN)
        self.label_20 = wx.StaticText(self, -1, _("New configuration"))
        self.label_21 = wx.StaticText(self, -1, _("Introduce the connection data"))
        self.label_11 = wx.StaticText(self, -1, _("Server"))
        self.text_ctrl_5 = wx.TextCtrl(self, -1, "")
        self.label_17 = wx.StaticText(self, -1, _("CN"))
        self.text_ctrl_6 = wx.TextCtrl(self, -1, "")
        self.label_18 = wx.StaticText(self, -1, _("Name"))
        self.text_ctrl_7 = wx.TextCtrl(self, -1, "")
        self.label_19 = wx.StaticText(self, -1, _("Password"))
        self.text_ctrl_9 = wx.TextCtrl(self, -1, "")
        self.btn_ok = wx.Button(self, -1, _("OK"))
        self.btn_cancel = wx.Button(self, -1, _("Cancel"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btn_ok_Click, self.btn_ok)
        self.Bind(wx.EVT_BUTTON, self.btn_cancel_Click, self.btn_cancel)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("frame_2"))
        self.label_9.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_10.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.combo_box_2.SetSelection(-1)
        self.label_20.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_21.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2 = wx.FlexGridSizer(6, 2, 0, 0)
        sizer_8.Add(self.label_9, 0, wx.TOP|wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 15)
        grid_sizer_2.Add(self.label_10, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        grid_sizer_2.Add(self.combo_box_2, 0, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 10)
        grid_sizer_2.Add(self.label_20, 0, wx.LEFT|wx.TOP|wx.ADJUST_MINSIZE, 10)
        grid_sizer_2.Add(self.label_21, 0, wx.LEFT|wx.TOP|wx.ADJUST_MINSIZE, 13)
        grid_sizer_2.Add(self.label_11, 0, wx.LEFT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        grid_sizer_2.Add(self.text_ctrl_5, 0, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 10)
        grid_sizer_2.Add(self.label_17, 0, wx.LEFT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        grid_sizer_2.Add(self.text_ctrl_6, 0, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 10)
        grid_sizer_2.Add(self.label_18, 0, wx.LEFT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        grid_sizer_2.Add(self.text_ctrl_7, 0, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 10)
        grid_sizer_2.Add(self.label_19, 0, wx.LEFT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_2.Add(self.text_ctrl_9, 0, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 10)
        grid_sizer_2.AddGrowableRow(0)
        grid_sizer_2.AddGrowableRow(2)
        grid_sizer_2.AddGrowableRow(3)
        grid_sizer_2.AddGrowableRow(4)
        grid_sizer_2.AddGrowableRow(5)
        grid_sizer_2.AddGrowableCol(1)
        sizer_8.Add(grid_sizer_2, 1, wx.ALL|wx.EXPAND, 20)
        sizer_9.Add(self.btn_ok, 0, wx.LEFT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 120)
        sizer_9.Add(self.btn_cancel, 0, wx.RIGHT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 80)
        sizer_8.Add(sizer_9, 0, wx.ALL|wx.ADJUST_MINSIZE, 15)
        sizer_7.Add(sizer_8, 1, wx.ALL|wx.EXPAND, 20)
        self.SetSizer(sizer_7)
        sizer_7.Fit(self)
        self.Layout()
        # end wxGlade

    def btn_ok_Click(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `btn_ok_Click' not implemented!"
        event.Skip()

    def btn_cancel_Click(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `btn_cancel_Click' not implemented!"
        event.Skip()

# end of class MyFrame


