# -*- coding: utf-8 -*-
# generated by wxGlade HG on Thu Feb 13 12:47:43 2014

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class MyPanel(wx.ScrolledWindow):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.ScrolledWindow.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyPanel.__set_properties
        self.SetSize((802, 602))
        self.SetBackgroundColour(wx.Colour(216, 216, 191))
        self.SetScrollRate(10, 10)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyPanel.__do_layout
        pass
        # end wxGlade

# end of class MyPanel


