# -*- coding: utf-8 -*-
# generated by wxGlade HG on Thu Feb 13 14:11:34 2014

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class NewConn(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: NewConn.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.CLIP_CHILDREN
        wx.Dialog.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        
        
        

    def __set_properties(self):
        # begin wxGlade: NewConn.__set_properties
        self.SetTitle("dialog_1")
        self.SetFocus()
        self.Hide()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: NewConn.__do_layout
        self.Layout()
        # end wxGlade

# end of class NewConn


