#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade HG on Fri Feb 14 10:31:59 2014

import wx
from MyFrame import MyFrame

class App_adm(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        Frm_Main = MyFrame(None, -1, "")
        self.SetTopWindow(Frm_Main)
        Frm_Main.Show()
        return 1

# end of class App_adm

if __name__ == "__main__":
    adm = App_adm(0)
    adm.MainLoop()
