# -*- coding: utf-8 -*-
# generated by wxGlade HG on Fri Feb 14 10:31:59 2014

import wx

# begin wxGlade: dependencies
import wx.grid
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.FRAME_FLOAT_ON_PARENT|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.Frm_Main_menubar = wx.MenuBar()
        self.File = wx.Menu()
        self.opc_newcon = wx.MenuItem(self.File, wx.NewId(), "New connection", "", wx.ITEM_NORMAL)
        self.File.AppendItem(self.opc_newcon)
        self.File.AppendSeparator()
        self.opc_quit = wx.MenuItem(self.File, wx.NewId(), "Quit", "", wx.ITEM_NORMAL)
        self.File.AppendItem(self.opc_quit)
        self.Frm_Main_menubar.Append(self.File, "File")
        self.SetMenuBar(self.Frm_Main_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.Frm_Main_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL|wx.TB_TEXT|wx.TB_HORZ_LAYOUT|wx.TB_HORZ_TEXT)
        self.SetToolBar(self.Frm_Main_toolbar)
        # Tool Bar end
        self.Grd_ListaUsrs = wx.grid.Grid(self, -1, size=(1, 1))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Active Directory Management")
        self.SetSize((771, 600))
        self.Frm_Main_toolbar.SetToolSeparation(5)
        self.Frm_Main_toolbar.Realize()
        self.Grd_ListaUsrs.CreateGrid(10, 4)
        self.Grd_ListaUsrs.SetColLabelValue(0, "Name")
        self.Grd_ListaUsrs.SetColLabelValue(1, "Surnname")
        self.Grd_ListaUsrs.SetColLabelValue(2, "Date")
        self.Grd_ListaUsrs.SetColLabelValue(3, "Patata")
        self.Grd_ListaUsrs.SetMinSize((600,400))
        self.Grd_ListaUsrs.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.Grd_ListaUsrs.SetForegroundColour(wx.Colour(49, 55, 57))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.Grd_ListaUsrs, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MyFrame


